### ISSUE TITLE
No spec for `artist_name=()`

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/ruby-collaborating-objects-lab#10]
A student was confused with the instructions compared to what the spec was looking for. The instructions ask for a method called `#artist_name=(artist_name_as_string)` on the Song class while the test looks for a method called `#artist=(artist_object)`. Is this intentional? Can this be made more clear?

**Comment by ruchiramani** [comment]
@aturkewi Can you send me a screenshot of where the artist_name_by_string is mentioned in the lab, can't seem to find it.

**Comment by aturkewi** [comment]
Sorry @ruchiramani, the readme says `#artist_name=(name)`, but that feels like it should be a string. It just caused confusion because the readme asks for a method of one name `#artist_name=()` and the spec tests for `#artist=()`.

**Comment by AnnJohn** [comment]
@ruchiramani can this issue be closed?
