### ISSUE TITLE
Divergence between the text and the tests

### ISSUE THREAD

**Issue by lukegrecki** [learn-co-curriculum/ruby-collaborating-objects-lab#13]
In the text under the `SONG#ARTIST=(ARTIST_NAME)` heading the `song#artist=` method is described as taking the `artist_name` as a string, whereas in the spec you have

```
  describe '#artist=' do
    it 'sets the artist object to belong to the song' do
      new_artist_object = Artist.new('King of Pop')
      song.artist = new_artist_object
      expect(song.artist).to eq(new_artist_object)
    end
  end
```

There the `#artist=` is expected to take an artist object. It also seems like the implementation of the method in the text is described as more involved (using `artist#find_or_create_by_name`) whereas the spec is only describing a simple attr_accessor.

**Comment by lukegrecki** [comment]
After looking at the solution it seems like the confusion mostly comes down to a simple typo (which I put a separate pull request in for), though I don't think the specs cover the whole implementation described and the degree of collaboration between song and artist.

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/ruby-collaborating-objects-lab/commit/12cc2a2f228f7ce1a436c65c8fc0c971ec7a4f31 -- thanks!
