### ISSUE TITLE
Issue - make tests and solution similar to sql

### ISSUE THREAD

**Issue by JeffKatzy** [learn-co-curriculum/ruby-collaborating-objects-lab#21]
Instead of having add_song methods as written, just have artist#add_song Song.create(artist: self)

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by aturkewi** [comment]
Example:
`artist.songs` should be doing something like `Song.select { |song| song.artist == self }` rather than storing the fact that an object and song are related on the song AND on the artist.

**Comment by AnnJohn** [comment]
@aturkewi can you make a pull request for this? thanks!

**Comment by aturkewi** [comment]
Working my way up to this lab @AnnJohn from the beginning of the section so things will make sense to the a student going through.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
