### ISSUE TITLE
Error in rspec

### ISSUE THREAD

**Issue by Niikwartey** [learn-co-curriculum/ruby-collaborating-objects-lab#23]
On line 38 of rspec/artist_spec.rb it says " expect(artist_1).to **e**(artist_2) " instead of " expect(artist_1).to **eq**(artist_2) " . I checked the original repo on github (to rule out a mistake on my end) and it too had a similar error.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by gj** [comment]
Fixed here: c461f87

Thanks @Niikwartey !
