### ISSUE TITLE
Need more explanation on how the MP3Importer is supposed to work...

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/ruby-collaborating-objects-lab#28]
I feel there is a lack of information provided on how the MP3Importer is supposed to work. Working with files in Ruby is something we haven't really seen yet in depth and I think we need some more information to be able to pass this lab...

**Comment by gj** [comment]
Hi @Ary770 !

Part of the challenge of this lab is figuring out how to work with files on your own. That's why we have this little hint in the MP3Importer section:
>Google around for how to get a list of files in a directory!

🙂
