### ISSUE TITLE
Missing Tests

### ISSUE THREAD

**Issue by mmb16** [learn-co-curriculum/ruby-collaborating-objects-lab#29]
Tests for the following methods are not included in the spec. However, the methods are used in tests for other methods.

add_songs
self.all
self.find
self.create

There may be more, those are the ones I've come across so far.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. Any chance you could point out a couple of examples where the methods above are used as 'helper methods' to other test but their core functionality is not tested?

As always, thanks for contributing! 💙
