### ISSUE TITLE
Improperly named methods

### ISSUE THREAD

**Issue by Hector-Ariceaga** [learn-co-curriculum/ruby-collaborating-objects-lab#32]
The README refers to the #add_song(song) method, but the rspec tests are looking for a #song method that "keeps track of an artist's songs". Simple fix might be to change rspec test to look for a #add_song(song) method with the same description as the current #song method.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
