### ISSUE TITLE
master/new master solution/newsolution very confusing!

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/ruby-collaborating-objects-lab#33]
I just got off a screenshare with a student doing this lab and the test for the Artist#songs method still uses the .add_song helper method. Since the new_solution branch does not do this I became very confused and it took quite a while to debug and figure out that the new_solution branch was not the one I wanted, given that the old master branch was what she was seeing, with the .add_song helper method expected. 

Here is the actual test spec in her wip branch:

  describe '#songs' do
    it 'keeps track of an artist\'s songs' do
      song_one = Song.new("Rock With You")
      song_two = Song.new("Smooth Criminal")
      artist.add_song(song_one) 
      artist.add_song(song_two)
      expect(artist.songs).to eq([song_one, song_two])
    end
  end

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
