### ISSUE TITLE
The README (and possibly the lab itself) needs to be updated.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/ruby-collaborating-objects-lab#34]
Hello. The README for this lab states that "the MP3 Importer will parse all the filenames in the db/mp3s folder and send the filenames to the Song class". However, the rspec tests only use the spec/fixtures/mp3s folder. I don't think the db/mp3s folder is ever used.

Thanks as always for looking into this!

Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
