### ISSUE TITLE
Add a section on gsub!

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/ruby-collaborating-objects-lab#35]
Hey guys! This is the second lab where gsub is the best approach to complete a method, and as far as I can remember there isn't an explanation of gsub in either Ruby section. I think given it's utility, it deserves it's own little section. Students can look it up, but it would be helpful to have it before the first lab application. 

Best,
Amanda

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
