### ISSUE TITLE
find_or_create_by_name(name) passing when incomplete test

### ISSUE THREAD

**Issue by fbohz** [learn-co-curriculum/ruby-collaborating-objects-lab#37]
Hi there I had issues with this lab and found out it was due that my find_or_create_by_name(name) was not returning an object when creating it so I had to refactor. Maybe create a rspec that tests that is returning and object?

This was my code passing when it was incomplete
```
  
  def self.find_or_create_by_name(artist_name)
      all.detect do |object| 
       artist = self.new(artist_name) unless object == artist_name
      end
 end 
```

This was refactored returning the object both cases:
```
  def self.find_or_create_by_name(name)
    name_match = all.detect{|object| object.name == name}
    if name_match
      name_match
    else
      new_object = self.new(name)
      new_object.save
      new_object
    end
  end
  ```

**Comment by maxwellbenton** [comment]
Hi @fbohz,

Thank you for spotting this and providing feedback. We updated this lab, adding an additional test for the `find_or_create_by_name` method that checks to make sure an `Artist` instance is always returned. This should prevent your provided example from passing and should help future students set this method up correctly prior to moving to the later tests.

We apologize for any inconvenience this issue may have caused. Thank you for contributing to a Learn lesson!
